### ISSUE TITLE
Highlights the product image with a blue background when you press the forward or back arrow repeatedly

### ISSUE THREAD

**Issue by BogdanaK77** [boarlabsxyz/Kavoon#40]
1. Defect ID: BG 03
2. Summary: Highlights the product image with a blue background when you press the forward or back arrow repeatedly
3. Description: When we are on the page of any product and scroll forward or backward with the arrows several times, the images begin to be highlighted (highlighted) with a blue background
4. Steps to Reproduce:
   1. Follow the link https://www.kavoon.com.ua/uk
   2. Click on any product
   3. Click the forward arrow several times on the images (or backward several times)
5. Expected Result: Product images are displayed correctly, without highlighting (highlighting) with a blue background
6. Actual Result: Product images start to be highlighted (highlighted) with a blue background
7. Attachments:https://github.com/user-attachments/assets/86e86bbc-200c-40e4-ab49-f5a7621a4e65
8. Severity: Major 
9. Priority: High
10. Notes:

**Comment by yuramax** [comment]
Test environment: https://kavoon-og6sppg11-kavoon.vercel.app/en
