### ISSUE TITLE
Incorrect size of the “Write a review” window

### ISSUE THREAD

**Issue by BogdanaK77** [boarlabsxyz/Kavoon#91]
1. Defect ID: BG 04
2. Summary: Incorrect size of the “Write a review” window
3. Description:  When I open the “Write a review” window, the window opens in the wrong size
4. Steps to Reproduce:
   1. Follow the link https://kavoon-1e7hfgsfx-kavoon.vercel.app/uk
   2. Click on any product
   3. Scroll down to the bottom to the “Write a review” button
   4. Click on the “Write a review” button
5. Expected Result: The correct size of the “Write a review” window is displayed
6. Actual Result: The wrong size of the “Write a review” window is displayed
7. Attachments: ![Знімок екрана (382)](https://github.com/user-attachments/assets/9ab62372-d947-4d08-bba7-ede763f18043)
8. Severity: Minor 
9. Priority: Medium
10. Notes:

**Comment by yuramax** [comment]
This issue is related to loading spinner and should be fixed once [task "Revert Added a loading spinner..."](https://github.com/boarlabsxyz/Kavoon/issues/105) will be done.

**Comment by yuramax** [comment]
@BogdanaK77, please see the fix on https://kavoon-c0916h6se-kavoon.vercel.app/en, thanks.
