### ISSUE TITLE
No indentation from header to text

### ISSUE THREAD

**Issue by BogdanaK77** [boarlabsxyz/Kavoon#92]
1. Defect ID: BG 05
2. Summary: No indentation from header to text
4. Description: When I opened the category “Shop” in the header, I see that the page does not have 80 px margin from the header to the text 
5. Steps to Reproduce:
   1. Follow the link https://kavoon-1e7hfgsfx-kavoon.vercel.app/uk
   2. Click the “Shop” category in the header 
6. Expected Result: Distance from the header to the text 80px
7. Actual Result: There is no distance from the header to the text
8. Attachments: ![Знімок екрана (381)](https://github.com/user-attachments/assets/b6b5da98-3d24-4ae9-9613-8a070d2a18b2)
9. Severity: Minor 
10. Priority: Medium
11. Notes:

**Comment by yuramax** [comment]
Environment for testing the task: https://kavoon-klunqdi62-kavoon.vercel.app/en.
