### ISSUE TITLE
All social networks are not displayed in the "Contact" slider in the "Support" window

### ISSUE THREAD

**Issue by BogdanaK77** [boarlabsxyz/Kavoon#95]
1. Defect ID: BG 06
2. Summary: All social networks are not displayed in the "Contact" slider in the "Support" window
3. Description: When I open the "Support" window and go to the "Contact" slider to select a social network, the slider does not show all social network options when it opens
4. Steps to Reproduce:
   1. Follow the link https://kavoon-1e7hfgsfx-kavoon.vercel.app/uk
   2. Click on the “Support” button
   3. Enter any text and click the Submit button
   4. Click on the arrow in the “Contact” cell
5. Expected Result: All social networks that can be selected are displayed
6. Actual Result: Not all social networks that can be selected are displayed
7. Attachments: https://github.com/user-attachments/assets/13cce9cb-db7e-4c38-85f7-102227cb86ed
8. Severity: Major
9. Priority: High
10. Notes:

**Comment by yuramax** [comment]
The issue comes up due to issues with loading spinner and will be fixed once [task "Revert Added a loading spinner ..."](https://github.com/boarlabsxyz/Kavoon/issues/105) will be done.

**Comment by yuramax** [comment]
@BogdanaK77, the fix should be found here - https://kavoon-c0916h6se-kavoon.vercel.app/en, thanks.

**Comment by BogdanaK77** [comment]
This error has been fixed. Social networks are displayed. But now the message is not sent to the messenger. A new task (bug report) has been created: https://github.com/boarlabsxyz/Kavoon/issues/112#issue-2711725455
